version: 0.0
os: linux
files:
 - source: script/newcode.sh
   destination: /var/www/html
Hooks:

 BeforeInstall:
 - location : script/installation.sh
   timeout : 300
   runas : root
ApplicationStart:
 - location : script/start.sh
   timeout : 300
   runas : root
runas : root
